// Funzione per generare gli URL delle immagini tramite identificativi di Unsplash
const IMG = (id, w = 900) =>
    `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

// Database delle città destinatarie del programma Erasmus con relativi dettagli e valutazioni
const citiesData = [
    {
        id: 1,
        city: "Siviglia",
        country: "Spagna",
        countryCode: "ES",
        profile: "Informatica e Telecomunicazioni",
        quality: 88,
        cost: 700,
        nightlife: 9.8,
        safety: 7.8,
        language: 6.0,
        transport: "Metropolitana, rete di biciclette (Sevici), autobus urbani, tram",
        uni: "L'Università di Siviglia è una delle più antiche d'Europa (fondata nel 1505). Il campus è immerso nel centro storico e gli studenti internazionali sono accolti da un'ottima rete ESN. La vita universitaria è vivace e piena di eventi culturali tutto l'anno.",
        food: "Espetos di sardine, Salmorejo, Torrijas, Vino de Naranja",
        tips: "Se vuoi risparmiare, cerca gli alloggi nel quartiere Triana, meno turistico ma autentico. Approfitta delle tapas gratuite con le bevande in molti bar locali!",
        year: "2025",
        rating: 9.4,
        yearGroup: "2025",
        cover: IMG("photo-1640799172468-d75176e6fa2f"),
        images: [
            IMG("photo-1640799172468-d75176e6fa2f"),
            IMG("photo-1713102834168-c8f0b3ed7ca9"),
            IMG("photo-1713805783213-a547542e2af5")
        ]
    },
    {
        id: 2,
        city: "Coimbra",
        country: "Portogallo",
        countryCode: "PT",
        profile: "Chimica e Biotecnologie Sanitarie",
        quality: 86,
        cost: 620,
        nightlife: 8.2,
        safety: 8.8,
        language: 5.5,
        transport: "Autobus urbani, treno regionale, funicolare, taxi economici",
        uni: "L'Università di Coimbra è Patrimonio UNESCO dal 2013. La famosa Biblioteca Joanina è uno dei luoghi più spettacolari del mondo. Gli studenti indossano ancora il tradizionale mantello nero e le canzoni accademiche (Fado di Coimbra) sono molto sentite.",
        food: "Leitão à Bairrada, Queijo da Serra, Arrufadas, Pastéis de Tentúgal",
        tips: "Visita il Mercado D. Pedro V per mangiare a poco prezzo. La Queima das Fitas (maggio) è la festa studentesca più importante: non perderla!",
        year: "2025",
        rating: 9.0,
        yearGroup: "2025",
        cover: "images/coimbra1.jpg",
        images: [
            "images/coimbra1.jpg",
            "images/coimbra3.jpg"
        ]
    },
    {
        id: 3,
        city: "Perpignan",
        country: "Francia",
        countryCode: "FR",
        profile: "Elettronica ed Elettrotecnica",
        quality: 83,
        cost: 780,
        nightlife: 7.5,
        safety: 8.2,
        language: 6.2,
        transport: "Treno TER, autobus urbani, biciclette a noleggio (Bip&Go), posizione strategica per viaggiare",
        uni: "L'Università di Perpignan Via Domitia è specializzata in scienze e tecnologia. La città è un crocevia tra cultura francese e catalana. Il Campus universitario è moderno e ben collegato. I laboratori di elettronica sono tra i più attrezzati della regione.",
        food: "Boles de picolat, Rousquilles, Cargolade, Crema catalana, Vini del Roussillon",
        tips: "Il treno per Collioure impiega 20 minuti: è uno dei borghi marittimi più belli di Francia. La domenica mattina c'è il mercato di Place Cassanyes, autentico e poco turistico.",
        year: "2025",
        rating: 8.7,
        yearGroup: "2025",
        cover: "images/perpignan3.jpg",
        images: [
            "images/perpignan3.jpg"
        ]
    },
    {
        id: 4,
        city: "Maribor",
        country: "Slovenia",
        countryCode: "SI",
        profile: "CAT - Costruzione Ambiente e Territorio",
        quality: 82,
        cost: 530,
        nightlife: 7.2,
        safety: 9.2,
        language: 5.8,
        transport: "Autobus urbani, treno, biciclette (Maribor è pianeggiante), funivia per Pohorje",
        uni: "L'Università di Maribor ha oltre 15.000 studenti ed è famosa per i dipartimenti di ingegneria e architettura. La città è molto sicura e gli sloveni sono estremamente accoglienti verso gli studenti in mobilità. Il centro storico è vivace e ricco di caffè.",
        food: "Prekmurska gibanica (dolce), Bograč (stufato), Koline (salumi), Vino Teran",
        tips: "Usa i Boni (buoni pasto studenti) – con 3-4€ mangi un pasto completo in molti ristoranti. La carta dello studente ti dà sconti su tutto, dai musei ai trasporti.",
        year: "2025",
        rating: 8.4,
        yearGroup: "2025",
        cover: "images/maribor1.jpg",
        images: [
            "images/maribor1.jpg",
            "images/maribor2.jpg",
            "images/maribor3.jpg"
        ]
    },
    {
        id: 5,
        city: "Heraklion",
        country: "Grecia",
        countryCode: "GR",
        profile: "Trasporti e Logistica",
        quality: 79,
        cost: 640,
        nightlife: 8.7,
        safety: 7.6,
        language: 6.8,
        transport: "Autobus urbani (KTEL), traghetti per le altre isole, scooter a noleggio, taxi economici",
        uni: "L'Università di Creta ha un campus moderno vicino alla città. Heraklion è un hub logistico importante per il Mediterraneo, perfetta per gli studenti di trasporti. Il Museo Archeologico e il Palazzo di Cnosso sono tappe obbligate. La vita notturna si concentra sul lungomare.",
        food: "Dakos (cracker cretese), Kalitsounia (formaggio), Staka (panna), Moussaka cretese, Raki",
        tips: "La student card ti fa entrare gratis in molti siti archeologici di Creta. Per mangiare bene e spendere poco, cerca le taverne nei vicoli laterali del mercato coperto.",
        year: "2025",
        rating: 8.2,
        yearGroup: "2025",
        cover: "images/heraklion1.jpg",
        images: [
            "images/heraklion1.jpg",
            "images/heraklion2.jpg",
            "images/heraklion3.jpg"
        ]
    },
    {
        id: 6,
        city: "Cracovia",
        country: "Polonia",
        countryCode: "PL",
        profile: "Meccanica e Meccatronica",
        quality: 84,
        cost: 480,
        nightlife: 9.0,
        safety: 8.5,
        language: 5.0,
        transport: "Tram, autobus, biciclette a noleggio (Wavelo), taxi economici",
        uni: "L'Università di Scienze e Tecnologia AGH è una delle migliori università tecniche dell'Europa centrale. Cracovia è ricca di storia, con il castello di Wawel e la piazza medievale più grande d'Europa. La vita studentesca è frenetica e il costo della vita è tra i più bassi dell'Unione Europea.",
        food: "Pierogi (ravioli polacchi), Żurek (zuppa acida), Oscypek (formaggio affumicato), Kielbasa, Birra Żywiec",
        tips: "Con la student card entri gratis in molti musei della città. Evita i ristoranti sul Rynek Główny (troppo turistici): vai nei vicoli del quartiere Kazimierz per mangiare ottimo cibo a prezzi stracciati.",
        year: "2025",
        rating: 8.9,
        yearGroup: "2025",
        cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/DJI_0352_Wawel.jpg/960px-DJI_0352_Wawel.jpg",
        images: [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/DJI_0352_Wawel.jpg/960px-DJI_0352_Wawel.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/20200516_Sukiennice_w_Krakowie_0909_9963.jpg/960px-20200516_Sukiennice_w_Krakowie_0909_9963.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Church_of_Our_Lady_Assumed_into_Heaven%2C_view_from_SW%2C_5_Mariacki_square%2C_Old_Town%2C_Krak%C3%B3w%2C_Poland.jpg/960px-Church_of_Our_Lady_Assumed_into_Heaven%2C_view_from_SW%2C_5_Mariacki_square%2C_Old_Town%2C_Krak%C3%B3w%2C_Poland.jpg"
        ]
    },
    {
        id: 7,
        city: "Tallinn",
        country: "Estonia",
        countryCode: "EE",
        profile: "Informatica e Telecomunicazioni",
        quality: 87,
        cost: 710,
        nightlife: 8.3,
        safety: 9.0,
        language: 8.5,
        transport: "Tram, autobus, filobus, treno (gratuiti con student card!), e-scooter",
        uni: "Tallinn University of Technology (TalTech) è un'eccellenza europea nell'informatica e nella cybersicurezza. L'Estonia è il paese più digitalizzato d'Europa e offre un ambiente unico per chi studia IT. La città vecchia medievale è Patrimonio UNESCO ed è a pochi minuti dal campus.",
        food: "Verivorst (sanguinaccio), Mulgikapsad (cavolo e maiale), Kiluvõileib (sandwich all'aringa), Vana Tallinn (liquore locale)",
        tips: "In Estonia la maggior parte dei servizi pubblici funzionano online: registrati subito al portale studenti digitale. I trasporti pubblici sono gratuiti per chi ha la student card di Tallinn.",
        year: "2025",
        rating: 8.6,
        yearGroup: "2025",
        cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/07-06-21-tallinn-by-RalfR-144.jpg/960px-07-06-21-tallinn-by-RalfR-144.jpg",
        images: [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/07-06-21-tallinn-by-RalfR-144.jpg/960px-07-06-21-tallinn-by-RalfR-144.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Ayuntamiento%2C_vistas_panor%C3%A1micas_desde_Toompea%2C_Tallin%2C_Estonia%2C_2012-08-05%2C_DD_21.JPG/960px-Ayuntamiento%2C_vistas_panor%C3%A1micas_desde_Toompea%2C_Tallin%2C_Estonia%2C_2012-08-05%2C_DD_21.JPG",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Estonia_1479_-_Alexander_Nevsky_Cathedral.jpg/960px-Estonia_1479_-_Alexander_Nevsky_Cathedral.jpg"
        ]
    },
    {
        id: 8,
        city: "Gand",
        country: "Belgio",
        countryCode: "BE",
        profile: "Chimica e Biotecnologie Sanitarie",
        quality: 91,
        cost: 850,
        nightlife: 8.8,
        safety: 8.6,
        language: 7.5,
        transport: "Tram, autobus De Lijn, biciclette (città quasi senza auto nel centro), treno verso Bruxelles (30 min)",
        uni: "Ghent University è tra le prime 100 università al mondo ed eccelle in scienze della vita e biotecnologie. Gand è considerata la città più studentesca del Belgio, con oltre 70.000 studenti su 260.000 abitanti. Il centro medievale con canali e torri è uno dei più belli d'Europa.",
        food: "Gentse Waterzooi (stufato di pollo/pesce), Cuberdons (caramelle viola), Speculoos, Birre artigianali belghe",
        tips: "Noleggia una bici appena arrivi: è il mezzo di trasporto principale in città. Il mercato del sabato mattina di Vrijdagsmarkt è imperdibile. Attenzione: molti documenti universitari sono in fiammingo!",
        year: "2025",
        rating: 9.1,
        yearGroup: "2025",
        cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Gent%2C_de_Graslei_vanaf_de_Korenlei_met_oeg24758tm61%2B25159_IMG_0447_2021-08-13_18.37.jpg/960px-Gent%2C_de_Graslei_vanaf_de_Korenlei_met_oeg24758tm61%2B25159_IMG_0447_2021-08-13_18.37.jpg",
        images: [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Gent%2C_de_Graslei_vanaf_de_Korenlei_met_oeg24758tm61%2B25159_IMG_0447_2021-08-13_18.37.jpg/960px-Gent%2C_de_Graslei_vanaf_de_Korenlei_met_oeg24758tm61%2B25159_IMG_0447_2021-08-13_18.37.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Gent_Gravensteen_R01.jpg/960px-Gent_Gravensteen_R01.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Graslei_gent_avondlicht.jpg/960px-Graslei_gent_avondlicht.jpg"
        ]
    },
    {
        id: 9,
        city: "Valencia",
        country: "Spagna",
        countryCode: "ES",
        profile: "Trasporti e Logistica",
        quality: 85,
        cost: 730,
        nightlife: 9.5,
        safety: 8.0,
        language: 6.5,
        transport: "Metropolitana, tram (T1/T3), autobus EMT, biciclette Valenbisi, vicinanza al porto",
        uni: "L'Universitat Politècnica de València è specializzata in ingegneria dei trasporti e logistica portuale. Il porto di Valencia è il più grande del Mediterraneo, rendendola la sede ideale per gli studenti di trasporti. Sole garantito 300 giorni l'anno e spiagge a 10 minuti dal centro.",
        food: "Paella valenciana (originale!), Horchata con fartons, Fideuà, All i Pebre, Orxata de chufa",
        tips: "La Paella si mangia solo a pranzo e mai la domenica sera (è considerato irrispettoso dai locali!). Il parco del Turia è perfetto per correre o andare in bici e collega tutta la città da nord a sud.",
        year: "2025",
        rating: 9.2,
        yearGroup: "2025",
        cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Ciutat_de_les_Arts_i_les_Ci%C3%A8ncies_at_night%2C_May_2017.jpg/960px-Ciutat_de_les_Arts_i_les_Ci%C3%A8ncies_at_night%2C_May_2017.jpg",
        images: [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Ciutat_de_les_Arts_i_les_Ci%C3%A8ncies_at_night%2C_May_2017.jpg/960px-Ciutat_de_les_Arts_i_les_Ci%C3%A8ncies_at_night%2C_May_2017.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Ciutat_de_les_Arts_i_les_Ci%C3%A8ncies.jpg/960px-Ciutat_de_les_Arts_i_les_Ci%C3%A8ncies.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Ayuntamiento_de_Valencia%2C_Espa%C3%B1a%2C_2014-06-30%2C_DD_121.JPG/960px-Ayuntamiento_de_Valencia%2C_Espa%C3%B1a%2C_2014-06-30%2C_DD_121.JPG"
        ]
    }
];
